### PR TITLE
Fix issue where request does not parse correct json key (new_hash vs newHash, new_username vs newUsername)

### PR DESCRIPTION
**Pull request by ranyodh**
### Summary

The PR has two changes:
1. Fix json key name issue
2. Updates swagger specs (not related to changes in this PR)

### Description

This PR includes fix for an issue where the following request fails to update username:

```
curl -X PUT ${baseUrl}/api/dex/v1/users/someuser@email.com
{
    "newUsername": "someuser2"
}'
```

But the following worked:
```
curl -X PUT ${baseUrl}/api/dex/v1/users/someuser@email.com
{
    "new_username": "someuser2"
}'
```
The issue was caused by the middleware using the default json marshaller (from "encoding/json"). With the proto generated code, the `runtime.HTTPBodyMarshaler` (https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/v2/runtime#HTTPBodyMarshaler) is a better choice as it correctly marshals the fields.

### Testing

I have added unit tests for the middleware that caused the issue. Also tested manually by deploying the custom image

### CODE REVIEW

**Comment by byDimasik** [comment]
@ranyodh 
Will this change require MKE Dashboard to update the request fields?

**Comment by ranyodh** [comment]
> @ranyodh Will this change require MKE Dashboard to update the request fields?

Yes, they UI is already using the correct keys

**Comment by byDimasik** [comment]
o

> > @ranyodh Will this change require MKE Dashboard to update the request fields?
> 
> Yes, they UI is already using the correct keys

oh, does it mean it's currently broken in the UI and will be fixed by this PR? But if it was broken, does it mean we never had it working with dashboard and don't know if the integration is working properly?

**Review by nwneisen — APPROVED** [review]

**Review by byDimasik — APPROVED** [review]
LGTM! Thanks for writing the tests. I am not very familiar with the codebase, but having tests helped me understand the change better.

**Comment by brianbancroft** [comment]
Note, there may be a chance this ticket resolved the bug

**Pull request merged**
